// Many of these are cribbed from RE2's test suite.

matiter!(wb1, r"\b", "");
matiter!(wb1s, r"\<", "");
matiter!(wb1e, r"\>", "");
matiter!(wb2, r"\b", "a", (0, 0), (1, 1));
matiter!(wb2s, r"\<", "a", (0, 0));
matiter!(wb2e, r"\>", "a", (1, 1));
matiter!(wb3, r"\b", "ab", (0, 0), (2, 2));
matiter!(wb3s, r"\<", "ab", (0, 0));
matiter!(wb3e, r"\>", "ab", (2, 2));
matiter!(wb4, r"^\b", "ab", (0, 0));
matiter!(wb4s, r"^\<", "ab", (0, 0));
matiter!(wb4e, r"^\>", "ab");
matiter!(wb5, r"\b$", "ab", (2, 2));
matiter!(wb5s, r"\<$", "ab");
matiter!(wb5e, r"\>$", "ab", (2, 2));
matiter!(wb6, r"^\b$", "ab");
matiter!(wb6s, r"^\<$", "ab");
matiter!(wb6e, r"^\>$", "ab");
matiter!(wb7, r"\bbar\b", "nobar bar foo bar", (6, 9), (14, 17));
matiter!(wb7ss, r"\<bar\<", "nobar bar foo bar");
matiter!(wb7se, r"\<bar\>", "nobar bar foo bar", (6, 9), (14, 17));
matiter!(wb7es, r"\>bar\<", "nobar bar foo bar");
matiter!(wb7ee, r"\>bar\>", "nobar bar foo bar");
matiter!(wb8, r"a\b", "faoa x", (3, 4));
matiter!(wb8s, r"a\<", "faoa x");
matiter!(wb8e, r"a\>", "faoa x", (3, 4));
matiter!(wb9, r"\bbar", "bar x", (0, 3));
matiter!(wb9s, r"\<bar", "bar x", (0, 3));
matiter!(wb9e, r"\>bar", "bar x");
matiter!(wb10, r"\bbar", "foo\nbar x", (4, 7));
matiter!(wb10s, r"\<bar", "foo\nbar x", (4, 7));
matiter!(wb10e, r"\>bar", "foo\nbar x");
matiter!(wb11, r"bar\b", "foobar", (3, 6));
matiter!(wb11s, r"bar\<", "foobar");
matiter!(wb11e, r"bar\>", "foobar", (3, 6));
matiter!(wb12, r"bar\b", "foobar\nxxx", (3, 6));
matiter!(wb12s, r"bar\<", "foobar\nxxx");
matiter!(wb12e, r"bar\>", "foobar\nxxx", (3, 6));
matiter!(wb13, r"(foo|bar|[A-Z])\b", "foo", (0, 3));
matiter!(wb13s, r"(foo|bar|[A-Z])\<", "foo");
matiter!(wb13e, r"(foo|bar|[A-Z])\>", "foo", (0, 3));
matiter!(wb14, r"(foo|bar|[A-Z])\b", "foo\n", (0, 3));
matiter!(wb14s, r"(foo|bar|[A-Z])\<", "foo\n");
matiter!(wb14e, r"(foo|bar|[A-Z])\>", "foo\n", (0, 3));
matiter!(wb15, r"\b(foo|bar|[A-Z])", "foo", (0, 3));
matiter!(wb15s, r"\<(foo|bar|[A-Z])", "foo", (0, 3));
matiter!(wb15e, r"\>(foo|bar|[A-Z])", "foo");
matiter!(wb16, r"\b(foo|bar|[A-Z])\b", "X", (0, 1));
matiter!(wb16ss, r"\<(foo|bar|[A-Z])\<", "X");
matiter!(wb16se, r"\<(foo|bar|[A-Z])\>", "X", (0, 1));
matiter!(wb16es, r"\>(foo|bar|[A-Z])\<", "X");
matiter!(wb16ee, r"\>(foo|bar|[A-Z])\>", "X");
matiter!(wb17, r"\b(foo|bar|[A-Z])\b", "XY");
matiter!(wb17ss, r"\<(foo|bar|[A-Z])\<", "XY");
matiter!(wb17se, r"\<(foo|bar|[A-Z])\>", "XY");
matiter!(wb17es, r"\>(foo|bar|[A-Z])\<", "XY");
matiter!(wb17ee, r"\>(foo|bar|[A-Z])\>", "XY");
matiter!(wb18, r"\b(foo|bar|[A-Z])\b", "bar", (0, 3));
matiter!(wb18ss, r"\<(foo|bar|[A-Z])\<", "bar");
matiter!(wb18se, r"\<(foo|bar|[A-Z])\>", "bar", (0, 3));
matiter!(wb18es, r"\>(foo|bar|[A-Z])\<", "bar");
matiter!(wb18ee, r"\>(foo|bar|[A-Z])\>", "bar");
matiter!(wb19, r"\b(foo|bar|[A-Z])\b", "foo", (0, 3));
matiter!(wb19ss, r"\<(foo|bar|[A-Z])\<", "foo");
matiter!(wb19se, r"\<(foo|bar|[A-Z])\>", "foo", (0, 3));
matiter!(wb19es, r"\>(foo|bar|[A-Z])\<", "foo");
matiter!(wb19ee, r"\>(foo|bar|[A-Z])\>", "foo");
matiter!(wb20, r"\b(foo|bar|[A-Z])\b", "foo\n", (0, 3));
matiter!(wb20ss, r"\<(foo|bar|[A-Z])\<", "foo\n");
matiter!(wb20se, r"\<(foo|bar|[A-Z])\>", "foo\n", (0, 3));
matiter!(wb20es, r"\>(foo|bar|[A-Z])\<", "foo\n");
matiter!(wb20ee, r"\>(foo|bar|[A-Z])\>", "foo\n");
matiter!(wb21, r"\b(foo|bar|[A-Z])\b", "ffoo bbar N x", (10, 11));
matiter!(wb21ss, r"\<(foo|bar|[A-Z])\<", "ffoo bbar N x");
matiter!(wb21se, r"\<(foo|bar|[A-Z])\>", "ffoo bbar N x", (10, 11));
matiter!(wb21es, r"\>(foo|bar|[A-Z])\<", "ffoo bbar N x");
matiter!(wb21ee, r"\>(foo|bar|[A-Z])\>", "ffoo bbar N x");
matiter!(wb22, r"\b(fo|foo)\b", "fo", (0, 2));
matiter!(wb22ss, r"\<(fo|foo)\<", "fo");
matiter!(wb22se, r"\<(fo|foo)\>", "fo", (0, 2));
matiter!(wb22es, r"\>(fo|foo)\<", "fo");
matiter!(wb22ee, r"\>(fo|foo)\>", "fo");
matiter!(wb23, r"\b(fo|foo)\b", "foo", (0, 3));
matiter!(wb23ss, r"\<(fo|foo)\<", "foo");
matiter!(wb23se, r"\<(fo|foo)\>", "foo", (0, 3));
matiter!(wb23es, r"\>(fo|foo)\<", "foo");
matiter!(wb23ee, r"\>(fo|foo)\>", "foo");
matiter!(wb24, r"\b\b", "");
matiter!(wb24ss, r"\<\<", "");
matiter!(wb24se, r"\<\>", "");
matiter!(wb24es, r"\>\<", "");
matiter!(wb24ee, r"\>\>", "");
matiter!(wb25, r"\b\b", "a", (0, 0), (1, 1));
matiter!(wb25ss, r"\<\<", "a", (0, 0));
matiter!(wb25se, r"\<\>", "a");
matiter!(wb25es, r"\>\<", "a");
matiter!(wb25ee, r"\>\>", "a", (1, 1));
matiter!(wb26, r"\b$", "");
matiter!(wb26s, r"\<$", "");
matiter!(wb26e, r"\>$", "");
matiter!(wb27, r"\b$", "x", (1, 1));
matiter!(wb27s, r"\<$", "x");
matiter!(wb27e, r"\>$", "x", (1, 1));
matiter!(wb28, r"\b$", "y x", (3, 3));
matiter!(wb28s, r"\<$", "y x");
matiter!(wb28e, r"\>$", "y x", (3, 3));
matiter!(wb29, r"\b.$", "x", (0, 1));
matiter!(wb29s, r"\<.$", "x", (0, 1));
matiter!(wb29e, r"\>.$", "x");
matiter!(wb30, r"^\b(fo|foo)\b", "fo", (0, 2));
matiter!(wb30ss, r"^\<(fo|foo)\<", "fo");
matiter!(wb30se, r"^\<(fo|foo)\>", "fo", (0, 2));
matiter!(wb30es, r"^\>(fo|foo)\<", "fo");
matiter!(wb30ee, r"^\>(fo|foo)\>", "fo");
matiter!(wb31, r"^\b(fo|foo)\b", "foo", (0, 3));
matiter!(wb31ss, r"^\<(fo|foo)\<", "foo");
matiter!(wb31se, r"^\<(fo|foo)\>", "foo", (0, 3));
matiter!(wb31es, r"^\>(fo|foo)\<", "foo");
matiter!(wb31ee, r"^\>(fo|foo)\>", "foo");
matiter!(wb32, r"^\b$", "");
matiter!(wb32s, r"^\<$", "");
matiter!(wb32e, r"^\>$", "");
matiter!(wb33, r"^\b$", "x");
matiter!(wb33s, r"^\<$", "x");
matiter!(wb33e, r"^\>$", "x");
matiter!(wb34, r"^\b.$", "x", (0, 1));
matiter!(wb34s, r"^\<.$", "x", (0, 1));
matiter!(wb34e, r"^\>.$", "x");
matiter!(wb35, r"^\b.\b$", "x", (0, 1));
matiter!(wb35ss, r"^\<.\<$", "x");
matiter!(wb35se, r"^\<.\>$", "x", (0, 1));
matiter!(wb35es, r"^\>.\<$", "x");
matiter!(wb35ee, r"^\>.\>$", "x");
matiter!(wb36, r"^^^^^\b$$$$$", "");
matiter!(wb36s, r"^^^^^\<$$$$$", "");
matiter!(wb36e, r"^^^^^\>$$$$$", "");
matiter!(wb37, r"^^^^^\b.$$$$$", "x", (0, 1));
matiter!(wb37s, r"^^^^^\<.$$$$$", "x", (0, 1));
matiter!(wb37e, r"^^^^^\>.$$$$$", "x");
matiter!(wb38, r"^^^^^\b$$$$$", "x");
matiter!(wb38s, r"^^^^^\<$$$$$", "x");
matiter!(wb38e, r"^^^^^\>$$$$$", "x");
matiter!(wb39, r"^^^^^\b\b\b.\b\b\b$$$$$", "x", (0, 1));
matiter!(wb39ss, r"^^^^^\<\<\<.\<\<\<$$$$$", "x");
matiter!(wb39se, r"^^^^^\<\<\<.\>\>\>$$$$$", "x", (0, 1));
matiter!(wb39es, r"^^^^^\>\>\>.\<\<\<$$$$$", "x");
matiter!(wb39ee, r"^^^^^\>\>\>.\>\>\>$$$$$", "x");
matiter!(wb40, r"\b.+\b", "$$abc$$", (2, 5));
matiter!(wb40ss, r"\<.+\<", "$$abc$$");
matiter!(wb40se, r"\<.+\>", "$$abc$$", (2, 5));
matiter!(wb40es, r"\>.+\<", "$$abc$$");
matiter!(wb40ee, r"\>.+\>", "$$abc$$");
matiter!(wb41, r"\b", "a b c", (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5));
matiter!(wb41s, r"\<", "a b c", (0, 0), (2, 2), (4, 4));
matiter!(wb41e, r"\>", "a b c", (1, 1), (3, 3), (5, 5));

matiter!(nb1, r"\Bfoo\B", "n foo xfoox that", (7, 10));
matiter!(nb2, r"a\B", "faoa x", (1, 2));
matiter!(nb3, r"\Bbar", "bar x");
matiter!(nb4, r"\Bbar", "foo\nbar x");
matiter!(nb5, r"bar\B", "foobar");
matiter!(nb6, r"bar\B", "foobar\nxxx");
matiter!(nb7, r"(foo|bar|[A-Z])\B", "foox", (0, 3));
matiter!(nb8, r"(foo|bar|[A-Z])\B", "foo\n");
matiter!(nb9, r"\B", "", (0, 0));
matiter!(nb10, r"\B", "x");
matiter!(nb11, r"\B(foo|bar|[A-Z])", "foo");
matiter!(nb12, r"\B(foo|bar|[A-Z])\B", "xXy", (1, 2));
matiter!(nb13, r"\B(foo|bar|[A-Z])\B", "XY");
matiter!(nb14, r"\B(foo|bar|[A-Z])\B", "XYZ", (1, 2));
matiter!(nb15, r"\B(foo|bar|[A-Z])\B", "abara", (1, 4));
matiter!(nb16, r"\B(foo|bar|[A-Z])\B", "xfoo_", (1, 4));
matiter!(nb17, r"\B(foo|bar|[A-Z])\B", "xfoo\n");
matiter!(nb18, r"\B(foo|bar|[A-Z])\B", "foo bar vNX", (9, 10));
matiter!(nb19, r"\B(fo|foo)\B", "xfoo", (1, 3));
matiter!(nb20, r"\B(foo|fo)\B", "xfooo", (1, 4));
matiter!(nb21, r"\B\B", "", (0, 0));
matiter!(nb22, r"\B\B", "x");
matiter!(nb23, r"\B$", "", (0, 0));
matiter!(nb24, r"\B$", "x");
matiter!(nb25, r"\B$", "y x");
matiter!(nb26, r"\B.$", "x");
matiter!(nb27, r"^\B(fo|foo)\B", "fo");
matiter!(nb28, r"^\B(fo|foo)\B", "foo");
matiter!(nb29, r"^\B", "", (0, 0));
matiter!(nb30, r"^\B", "x");
matiter!(nb31, r"^\B\B", "", (0, 0));
matiter!(nb32, r"^\B\B", "x");
matiter!(nb33, r"^\B$", "", (0, 0));
matiter!(nb34, r"^\B$", "x");
matiter!(nb35, r"^\B.$", "x");
matiter!(nb36, r"^\B.\B$", "x");
matiter!(nb37, r"^^^^^\B$$$$$", "", (0, 0));
matiter!(nb38, r"^^^^^\B.$$$$$", "x");
matiter!(nb39, r"^^^^^\B$$$$$", "x");

// These work for both Unicode and ASCII because all matches are reported as
// byte offsets, and « and » do not correspond to word boundaries at either
// the character or byte level.
matiter!(unicode1, r"\bx\b", "«x", (2, 3));
matiter!(unicode1ss, r"\<x\<", "«x");
matiter!(unicode1se, r"\<x\>", "«x", (2, 3));
matiter!(unicode1es, r"\>x\<", "«x");
matiter!(unicode1ee, r"\>x\>", "«x");
matiter!(unicode2, r"\bx\b", "x»", (0, 1));
matiter!(unicode2ss, r"\<x\<", "x»");
matiter!(unicode2se, r"\<x\>", "x»", (0, 1));
matiter!(unicode2es, r"\>x\<", "x»");
matiter!(unicode2ee, r"\>x\>", "x»");
